In [1]:
import pandas as pd
df = pd.read_excel("/content/drive/MyDrive/Ecommerce.xlsx")
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595379968,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326769920,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792630016,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920209920,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631879936,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [2]:
df.info() # check data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_time     400 non-null    object
 1   event_type     400 non-null    object
 2   product_id     400 non-null    int64
 3   category_id    400 non-null    int64
 4   category_code  258 non-null    object
 5   brand          339 non-null    object
 6   price          400 non-null    float64
 7   user_id        400 non-null    int64
 8   user_session   400 non-null    object
dtypes: float64(1), int64(3), object(5)
memory usage: 28.3+ KB

In [3]:
df = df.dropna() # remove missing values

In [4]:
df = df.drop_duplicates()

In [5]:
df.isnull().sum()

event_time       0
event_type       0
product_id       0
category_id      0
category_code    0
brand            0
price            0
user_id          0
user_session     0
dtype: int64

In [6]:
df ['event_time'] = pd.to_datetime(df['event_time'])  # convert time

In [12]:
df.dtypes

event_time       datetime64[ns, UTC]
event_type                    object
product_id                     int64
category_id                    int64
category_code                 object
brand                         object
price                        float64
user_id                        int64
user_session                  object
purchase                       int64
dtype: object

In [13]:
df = df[df['price'] > 0] # filtered important data

In [7]:
df['purchase'] = df['event_type'].apply(lambda x:1 if x == 'purchase' else 0) # create purchase column

In [14]:
df['hour'] = df['event_time'].dt.hour
df['day'] = df['event_time'].dt.day

In [15]:
user_data = df.groupby('user_id').agg({
    'event_type': 'count',   # activity level
    'price': 'mean',
    'purchase': 'max'
}).reset_index()

user_data.columns = ['user_id', 'activity', 'avg_price', 'purchase']

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X = user_data[['activity', 'avg_price']]
y = user_data['purchase']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LogisticRegression()
model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9642857142857143

In [17]:
df.to_csv("cleaned_ecommerce.csv", index=False)

In [18]:
from google.colab import files
files.download("cleaned_ecommerce.csv")